- name: Retrieve default certification
  ansible.builtin.include_role:
    name: common
    tasks_from: retrieve_default_certification
  vars:
    common_crt_output_to_var: "tls_crt"
    common_key_output_to_var: "tls_key"
    common_ca_output_to_var: "ca_crt"

- name: Prepare yaml file for custom IAF TLS Secret
  ansible.builtin.template:
    src: iaf/iaf-tls-secret.yaml.j2
    dest: "{{ cp4ba_output_directory }}/iaf-tls-secret.yaml"
    mode: u+rwx

- name: Add custom IAF TLS Secret
  kubernetes.core.k8s:
    state: present
    force: false
    merge_type: merge
    src: "{{ cp4ba_output_directory }}/iaf-tls-secret.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Wait for AutomationUIConfig CRD to be Established
  ansible.builtin.include_role:
    name: common
    tasks_from: wait-crd
  vars:
    common_crd_name: automationuiconfigs.core.automation.ibm.com

- name: Wait for Deployments to be Available
  ansible.builtin.include_role:
    name: common
    tasks_from: wait-resource-condition
  vars:
    common_api_version: v1
    common_resource_kind: Deployment
    common_resource_name: "{{ item }}"
    common_resource_namespace: "{{ cp4ba_project_name }}"
    common_condition_name: Available
    common_retries: 80
    common_delay: 15
  with_items:
    - iaf-core-operator-controller-manager
    - iaf-operator-controller-manager

- name: Prepare yaml file for AutomationUiConfig CR
  ansible.builtin.template:
    src: iaf/automationuiconfig.yaml.j2
    dest: "{{ cp4ba_output_directory }}/automationuiconfig.yaml"
    mode: u+rwx

# Based on https://www.ibm.com/docs/en/cloud-paks/1.0?topic=foundation-custom-resources#automationuiconfig
# Based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/latest?topic=certificates-providing-root-ca-certificate Note
- name: Add AutomationUIConfig CR
  kubernetes.core.k8s:
    state: present
    force: false
    merge_type: merge
    src: "{{ cp4ba_output_directory }}/automationuiconfig.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Wait for AutomationUIConfig instance Ready state
  ansible.builtin.include_role:
    name: common
    tasks_from: wait-resource-condition
  vars:
    common_api_version: core.automation.ibm.com/v1beta1
    common_resource_kind: AutomationUIConfig
    common_resource_name: iaf-system
    common_resource_namespace: "{{ cp4ba_project_name }}"
    common_condition_name: Ready
    common_retries: 80
    common_delay: 15
