---
- name: Check if Portworx is installed
  block:
    - name: Check if portworx daemonset exists
      command: oc get ds -n kube-system portworx
      register: portworx_ds_exists
      ignore_errors: true

    - name: Fail if portworx daemonset does not exist
      fail:
        msg: "Portworx is not installed on the cluster"
      when: portworx_ds_exists.rc != 0
  tags:
    - portworx

- name: Create Portworx storage classes for CP4D
  block:
    - name: Create Portworx storage class YAML file
      template:
        src: pwx_cp4d_storage_classes.j2
        dest: "{{ pwx_storage_classes_file }}"

    - name: Apply Portworx storage classes YAML file
      command: oc apply -f "{{ pwx_storage_classes_file }}"
      changed_when: "'created' in result.stdout"
  vars:
    pwx_storage_classes_file: "{{ status_dir }}/openshift/pwx_cp4d_storage_classes.yaml"

