---
# Currently, Cloud Pak Deployer supports installation and configuration of Portworx on IBM Cloud only,
# but there are situations with existing OpenShift clusters where Portworx is already installed. 

- name: Validate cloud_platform is implemented
  fail: msg="cloud_platform {{ cloud_platform }} is not implemented, current implemented cloud platforms are {{ implemented_cloud_platform_types }} "
  when: "cloud_platform not in implemented_cloud_platform_types"

- include_tasks: ibmcloud-pwx.yml  
  when: cloud_platform == 'ibm-cloud'  

- include_tasks: existing-ocp-pwx.yml  
  when: cloud_platform == 'existing-ocp'  