- name: Remove usage Config Map
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: ConfigMap
    name: usage
    namespace: apollo-one-shot
    force: false
    wait: true
    wait_sleep: 15
    wait_timeout: 15
