---

# ------------ PREPARATION ------------------------------------------

- debug:
    msg: "Handling CP4BA cluster {{ current_cp4ba_cluster.project }}"

- set_fact:
    _cpd_accept_licenses: "{{ current_cp4ba_cluster.accept_licenses | default(cpd_accept_licenses) | default(False) }}"

- name: Fail if licenses were not accepted
  fail:
    msg: "You must accept the licenses, either in the cp4ba object with accept_licenses: True, or by specifying --accept-all-licenses at the command line"
  when: not (_cpd_accept_licenses | bool)

- set_fact:
    _current_openshift_cluster: "{{ all_config.openshift | json_query(query) | first | default({}) }}"
  vars:
    query: >-
      [?name=='{{ current_cp4ba_cluster.openshift_cluster_name }}']

- name: Download and activate OpenShift client for version {{ _current_openshift_cluster.ocp_version }}
  include_role:
    name: openshift-download-client
  vars:
    _p_ocp_version: "{{ _current_openshift_cluster.ocp_version }}"

- name: Login to the OpenShift cluster
  include_role:
    name: openshift-login
  vars:
    _p_openshift_cluster_name: "{{ current_cp4ba_cluster.openshift_cluster_name }}"

- name: Get IBM Entitled Registry key
  include_role: 
    name: vault-get-secret
  vars:
    secret_name: "ibm_cp_entitlement_key"
    secret_group: "{{ environment_name }}"

- set_fact:
    ibm_cp_entitlement_key: "{{ secret_value }}"

- fail:
    msg: "No image registry name specified for CP4BA but cannot pull from entitled registry because of missing entitlement key in vault"
  when: ibm_cp_entitlement_key == "" and (current_cp4ba_cluster.image_registry_name | default("")) == ""

- set_fact:
    entitled_auth: "{{ entitled_registry_username }}:{{ ibm_cp_entitlement_key }}"
  when: ibm_cp_entitlement_key != ""

- set_fact:
    use_entitled_registry: False

- name: Use entitled registry if entitlement key available and no image registry name specified
  set_fact:
    use_entitled_registry: True
  when:
  - (current_cp4ba_cluster.image_registry_name | default("")) == ""

- name: Connect to private image registry
  include_role: 
    name: connect-private-image-registry
  when:
  - (current_cp4ba_cluster.image_registry_name | default("")) != ""

- name: Remove Cloud Pak for Business Automation directory for generated files
  file:
    path: "{{ status_dir }}/cp4ba"
    state: absent

- name: Create Cloud Pak for Business Automation directory for generated files
  file:
    path: "{{ status_dir }}/cp4ba"
    state: directory

- name: Prepare OpenShift cluster for Cloud Pak for Business Automation
  include_role:
    name: cp4ba-prepare-openshift

# ------------ SETTING PROCESSING FACTS -----------------------------


### TO BE COMPLETED