---

- name: Check if admin password secret name is already defined
  set_fact: 
    _dp_admin_password_secret: "{{ instance_properties.admin_password_secret | default('') }}"

- name: Construct admin password secret name if it is not yet defined
  block:

  - name: Define admin password secret name
    set_fact:
      _dp_admin_password_secret: "{{ instance_properties.name }}-admin-password"

  - name: Define admin password
    set_fact:
      _dp_admin_password: "{{ instance_properties.admin_password | default('passw0rd') }}"

  - name: Create admin password secret
    shell: |
      oc create secret generic {{_dp_admin_password_secret}} --from-literal=password={{_dp_admin_password}} -n {{current_cp4i_cluster.project}}

  when: "_dp_admin_password_secret | trim | length == 0"